// webshop-next/common/components/ShopItem.tsx
import { FC } from 'react';
import useCart from '../hooks/useCart';
import { ShopItemType } from '../types';

interface ShopItemProps {
	item: ShopItemType;
	index: number;
}

const ShopItem: FC<ShopItemProps> = ({ index, item }) => {
	const { addToCart } = useCart();
	return (
		<div
			id={'shopitem-' + item._id}
			className='w-full flex flex-col border border-transparent hover:bg-gray-50 transition-colors'
		>
			<img
				src={item.image}
				alt={item.name}
				className='w-full h-48 object-contain'
			/>
			<div className='p-2'>
				<p className='text-lg font-medium mb-1'>{item.name}</p>
				<p className='mb-3'>{item.description}</p>
				<p className='text-right'>NOK {item.price},-</p>
				<button
					className='bg-black w-full py-1.5 px-3 text-white mt-3 hover:bg-black/80'
					onClick={() => addToCart(item)}
				>
					Add to cart
				</button>
			</div>
		</div>
	);
};

export default ShopItem;

// webshop-svelte/src/components/ShopItem.svelte
<script lang="ts">
	import { addToCart } from "$stores/cart";
	import type { ShopItemType } from "src/types";
	import { fade, fly } from 'svelte/transition';

    export let item: ShopItemType;
    export let index: number;

</script>

<div id={"shopitem-" + item._id} class="w-full flex flex-col border border-transparent hover:bg-gray-50 transition-colors"  in:fly="{{ y: 200, duration: 400 + (index * 50) }}" out:fade="{{duration: 200}}">
    <img src={item.image} alt={item.name} class="w-full h-48 object-contain" />
    <div class="p-2">
        <p class="text-lg font-medium mb-1">{item.name}</p>
        <p class="mb-3">{item.description}</p>
        <p class="text-right">NOK {item.price},-</p>
        <button class="bg-black w-full py-1.5 px-3 text-white mt-3 hover:bg-black/80" on:click={() => addToCart(item)}>Add to cart</button>
    </div>
</div>
